<?php

namespace OpenRegion\PhpcadesMeta;

class CPHashedDataPhpStormMeta implements PhpStormMetaInterface
{
  public static function getMeta(): string
  {
    return <<<'PHP'
  expectedArguments(
    \CPHashedData::set_Algorithm(),
    0,
    HASH_ALGORITHM_SHA1,
    HASH_ALGORITHM_MD2,
    HASH_ALGORITHM_MD4,
    HASH_ALGORITHM_MD5,
    HASH_ALGORITHM_SHA_256,
    HASH_ALGORITHM_SHA_384,
    HASH_ALGORITHM_SHA_512,
    HASH_ALGORITHM_GOSTR_3411,
    CADESCOM_HASH_ALGORITHM_CP_GOST_3411,
    CADESCOM_HASH_ALGORITHM_CP_GOST_3411_2012_256,
    CADESCOM_HASH_ALGORITHM_CP_GOST_3411_2012_512,
    CADESCOM_HASH_ALGORITHM_CP_GOST_3411_HMAC,
    CADESCOM_HASH_ALGORITHM_CP_GOST_3411_2012_256_HMAC,
    CADESCOM_HASH_ALGORITHM_CP_GOST_3411_2012_512_HMAC,
  );

  expectedReturnValues(
    \CPHashedData::get_Algorithm(),
    HASH_ALGORITHM_SHA1,
    HASH_ALGORITHM_MD2,
    HASH_ALGORITHM_MD4,
    HASH_ALGORITHM_MD5,
    HASH_ALGORITHM_SHA_256,
    HASH_ALGORITHM_SHA_384,
    HASH_ALGORITHM_SHA_512,
    HASH_ALGORITHM_GOSTR_3411,
    CADESCOM_HASH_ALGORITHM_CP_GOST_3411,
    CADESCOM_HASH_ALGORITHM_CP_GOST_3411_2012_256,
    CADESCOM_HASH_ALGORITHM_CP_GOST_3411_2012_512,
    CADESCOM_HASH_ALGORITHM_CP_GOST_3411_HMAC,
    CADESCOM_HASH_ALGORITHM_CP_GOST_3411_2012_256_HMAC,
    CADESCOM_HASH_ALGORITHM_CP_GOST_3411_2012_512_HMAC,
  );

  expectedArguments(
    \CPHashedData::set_DataEncoding(),
    0,
    STRING_TO_UCS2LE,
    BASE64_TO_BINARY,
  );

  expectedReturnValues(
    \CPHashedData::get_DataEncoding(),
    STRING_TO_UCS2LE,
    BASE64_TO_BINARY,
  );
PHP;
  }
}
